### ISSUE TITLE
Opening and closing tabs creates multiple queries

### ISSUE THREAD

**Issue by FrederikSchlemmer** [adessoAG/GitStalkerBootstrapUI#11]
Closing and opening new tabs increases the number of requests to the back end. The 'Data-Pull.service' is called several times. 

![image](https://user-images.githubusercontent.com/35023083/46850459-4d749380-cdf4-11e8-855a-dfecae2490cd.png)

**Comment by FrederikSchlemmer** [comment]
Somehow this problem seems to be fixed...

**Comment by dariobraun** [comment]
Fixed in #23
