### ISSUE TITLE
Incorrect organization entries are displayed with an empty page

### ISSUE THREAD

**Issue by FrederikSchlemmer** [adessoAG/GitStalkerBootstrapUI#14]
After the incorrect name of an organization has been entered, a tab with incorrect name is opened, but an empty page remains.

![image](https://user-images.githubusercontent.com/35023083/46852787-6719d900-cdfc-11e8-9eac-b42ef7f887d7.png)

**Comment by dariobraun** [comment]
Fixed by #39
