### ISSUE TITLE
Second enterprise failure

### ISSUE THREAD

**Issue by tinne** [adessoAG/GitStalkerBootstrapUI#2]
Once I stalk one enterprise, I can enter the name of other enterprises, but the tabs that open will again show data w.r.t. the first enterprise selected. Only the tab has the other name (misleadingly).

**Comment by tinne** [comment]
This only happens most of the time and may be due to the sample data (which, by the may, mixes case in Microsoft vs. microsoft with spurious effect).

**Comment by dariobraun** [comment]
@tinne Thanks for submitting! This is bug occurs when an organization is requested that is not yet saved in the database. We will need to add visual feedback for the user so it is clear that the backend is working on gathering the data.
