### ISSUE TITLE
No user feedback for error and long backend processing

### ISSUE THREAD

**Issue by dariobraun** [adessoAG/GitStalkerBootstrapUI#34]
When an organization is requested and the backend has to gather the information from the GitHub api, the user should be informed that he will have to wait some time before the data can be displayed. Ideally the user is given an estimated time of completion. 
Same goes for errors. When an organization is requested that doesn't exist on GitHub, the user must be informed.

**Comment by FrederikSchlemmer** [comment]
Fixed by #39
