### ISSUE TITLE
Tab names are incorrect

### ISSUE THREAD

**Issue by dariobraun** [adessoAG/GitStalkerBootstrapUI#37]
The organization names displayed on the tabs are not linked to the actual organization objects, therefore they might not represent the actual name displayed on github.com.

**Comment by dariobraun** [comment]
[app.component.ts](https://github.com/adessoAG/GitStalkerBootstrapUI/blob/master/src/app/app.component.ts) should be the file look at here.

**Comment by FrederikSchlemmer** [comment]
Fixed by #47
